import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireUser, canManageCampaign } from '@/lib/auth';
import { createServiceClient } from '@/lib/supabase-server';
import { DocumentUploader } from '@/components/dashboard/DocumentUploader';
import { MediaManager } from '@/components/dashboard/MediaManager';

export default async function Page({params}:{params:Promise<{id:string}>}){
  const {id}=await params;const {user,profile}=await requireUser();const s=createServiceClient();const isSuperAdmin=profile?.role==='super_admin';const canSeeAll=canManageCampaign(profile?.role);
  let campaignQuery=s.from('campaigns').select('*, beneficiaries(display_name,consent_status,identity_status), payment_destinations(account_holder_name,verification_status)').eq('id',id);
  if(!canSeeAll)campaignQuery=campaignQuery.eq('owner_id',user.id);
  const {data:c}=await campaignQuery.maybeSingle();if(!c)notFound();
  const [{data:checksData},{data:docsData},{data:changeData},{data:queryData},{data:mediaData}]=await Promise.all([
    s.from('compliance_checks').select('*').eq('campaign_id',id).order('created_at'),
    s.from('verification_documents').select('id,kind,file_name,status,uploaded_at').eq('campaign_id',id).order('uploaded_at',{ascending:false}),
    s.from('campaign_change_requests').select('*').eq('campaign_id',id).order('created_at',{ascending:false}).limit(20),
    s.from('campaign_queries').select('*').eq('campaign_id',id).order('created_at',{ascending:false}),
    s.from('campaign_media').select('id,kind,title,status,reviewer_note,created_at,is_primary,url').eq('campaign_id',id).order('created_at',{ascending:false})
  ]);
  const checks=checksData??[],docs=docsData??[],changes=changeData??[],queries=queryData??[],media=mediaData??[];
  return <><section className="cms-hero"><div className="shell"><div className="cms-hero-row"><div><div className="eyebrow">{c.reference_code}</div><h1>{c.title}</h1><div className="cms-meta-row"><span className={`status-pill ${c.risk_level}`}>{String(c.status).replaceAll('_',' ')}</span>{isSuperAdmin&&<span className="cms-role-badge">Direct edit enabled</span>}</div></div><Link className="button secondary" href={`/campaigns/${c.slug}`} target="_blank">View live campaign</Link></div></div></section><section className="cms-section"><div className="shell"><div className="cms-toolbar cms-toolbar-tabs"><div><Link className="button" href={`/dashboard/campaigns/${id}/edit`}>Edit campaign</Link><Link className="button secondary" href={`/dashboard/campaigns/${id}/updates`}>Updates</Link><Link className="button secondary" href={`/dashboard/campaigns/${id}/donations`}>Donations</Link><Link className="button secondary" href={`/dashboard/campaigns/${id}/payouts`}>Payouts</Link></div></div><div className="cms-layout"><main className="cms-main">
    {queries.some((q:any)=>q.status==='open')&&!isSuperAdmin&&<div className="card cms-panel"><h2>Information requested by Good Cause</h2>{queries.filter((q:any)=>q.status==='open').map((q:any)=><div className="task-row" key={q.id}><div><strong>{q.title}</strong><span>{q.message}</span></div><Link className="button small" href={`/dashboard/campaigns/${id}/queries`}>Respond</Link></div>)}</div>}
    <div className="card cms-panel"><div className="cms-panel-head"><div><span className="cms-kicker">Campaign content</span><h2>Quick management</h2></div><Link className="text-link" href={`/dashboard/campaigns/${id}/edit`}>Edit all text</Link></div><div className="cms-summary-grid"><div><span>Status</span><strong>{String(c.status).replaceAll('_',' ')}</strong></div><div><span>Target</span><strong>NZ${(Number(c.target_cents||0)/100).toLocaleString()}</strong></div><div><span>Location</span><strong>{c.location||'Not set'}</strong></div><div><span>Media</span><strong>{media.length}</strong></div></div></div>
    <div className="card cms-panel"><div className="cms-panel-head"><div><span className="cms-kicker">Media library</span><h2>Campaign images and references</h2></div></div>{media.length===0?<p className="muted">No media added yet.</p>:<div className="cms-media-grid">{media.map((m:any)=><div className="cms-media-item" key={m.id}>{m.kind==='image'&&m.status==='approved'?<img src={`/api/media/${m.id}`} alt={m.title}/>:<div className="cms-media-placeholder">{m.kind}</div>}<div><strong>{m.title}</strong><span>{m.is_primary?'Campaign cover · ':''}{m.status}</span>{m.url&&<a href={m.url} target="_blank" rel="noreferrer">Open link</a>}</div></div>)}</div>}</div>
    {!isSuperAdmin&&<><div className="card cms-panel"><h2>Compliance progress</h2>{checks.length===0?<p className="muted">No compliance items.</p>:checks.map((x:any)=><div className="task-row" key={x.id}><div><strong>{x.label}</strong><span>{x.reviewer_note||'Review in progress'}</span></div><b className={`check-state ${x.status}`}>{String(x.status).replaceAll('_',' ')}</b></div>)}</div><div className="card cms-panel"><h2>Pending and recent changes</h2>{changes.length===0?<p className="muted">No campaign change requests yet.</p>:changes.map((r:any)=><div className="task-row" key={r.id}><div><strong>{r.summary||'Campaign change'}</strong><span>{r.admin_note||`Submitted ${new Date(r.created_at).toLocaleString('en-NZ')}`}</span></div><b>{r.status}</b></div>)}</div></>}
  </main><aside className="cms-sidebar">{!isSuperAdmin&&<DocumentUploader campaignId={id}/>}<MediaManager campaignId={id} isSuperAdmin={isSuperAdmin}/>{!isSuperAdmin&&<div className="card cms-panel"><h3>Approval control</h3><p className="muted">Changes to a live campaign are reviewed before publication.</p></div>}</aside></div></div></section></>;
}
