import { NextResponse } from 'next/server';
import { createServerSupabaseClient, createServiceClient } from '@/lib/supabase-server';
import { sendEmail } from '@/lib/email';
import { createNotification, notifyAdmins } from '@/lib/notifications';

function slugify(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,70)}
export async function POST(request:Request){
  const auth=await createServerSupabaseClient(); const {data:{user}}=await auth.auth.getUser(); if(!user)return NextResponse.json({error:'Please log in first.'},{status:401});
  const body=await request.json(); const service=createServiceClient(); const now=new Date(); const ref=`GC-${now.getFullYear()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`; const slug=`${slugify(body.title||'cause')}-${Math.random().toString(36).slice(2,6)}`;
  await service.from('profiles').upsert({id:user.id,email:user.email,full_name:body.fullName||user.user_metadata?.full_name||'',mobile:body.mobile||null,updated_at:new Date().toISOString()},{onConflict:'id'});
  const {data:fp,error:fpe}=await service.from('fundraiser_profiles').upsert({user_id:user.id,fundraiser_type:body.fundraiserType,legal_name:body.fullName,address:body.address,country_code:'NZ',contact_status:'verified',identity_status:'pending'},{onConflict:'user_id'}).select().single(); if(fpe)return NextResponse.json({error:fpe.message},{status:400});
  const country=body.beneficiaryCountry==='New Zealand'?'NZ':body.beneficiaryCountry==='Australia'?'AU':'OTHER';
  const {data:b,error:be}=await service.from('beneficiaries').insert({display_name:body.beneficiaryName,legal_name:body.beneficiaryName,beneficiary_type:body.fundraiserType==='individual_self'?'self':'third_party',country_code:country,relationship_to_fundraiser:body.beneficiaryRelationship,consent_status:body.fundraiserType==='for_someone_else'?(body.beneficiaryConsent?'pending':'not_started'):'verified',identity_status:'pending'}).select().single(); if(be)return NextResponse.json({error:be.message},{status:400});
  const {data:pd,error:pde}=await service.from('payment_destinations').insert({beneficiary_id:b.id,provider:'bank_transfer',account_holder_name:body.paymentName,bank_name:body.bankName,bank_account_number:body.bankAccountNumber,country_code:country,verification_status:'pending',is_active:true}).select().single(); if(pde)return NextResponse.json({error:pde.message},{status:400});
  const enhanced=body.fundraiserType==='for_someone_else'||country!=='NZ'||Number(body.target||0)>=15000||body.category==='Emergency relief';
  const {data:c,error:ce}=await service.from('campaigns').insert({owner_id:user.id,fundraiser_profile_id:fp.id,beneficiary_id:b.id,payment_destination_id:pd.id,slug,reference_code:ref,title:body.title,summary:(body.purpose||'').slice(0,220),story:body.purpose,category:body.category,location:body.address,target_cents:body.target?Math.round(Number(body.target)*100):null,currency:'NZD',status:'submitted',risk_level:enhanced?'enhanced':'standard',risk_reason:enhanced?'Campaign characteristics require enhanced review.':null}).select().single(); if(ce)return NextResponse.json({error:ce.message},{status:400});
  const checks=[['identity','Fundraiser identity'],['beneficiary','Beneficiary verification'],['beneficiary_consent','Beneficiary consent'],['payment_destination','Payment destination'],['purpose_evidence','Purpose and supporting evidence'],['risk_screening','Risk screening'],['human_review','Human moderation']].map(([check_key,label])=>({campaign_id:c.id,check_key,label,required:!(check_key==='beneficiary_consent'&&body.fundraiserType!=='for_someone_else'),status:check_key==='beneficiary_consent'&&body.fundraiserType!=='for_someone_else'?'verified':'pending'}));
  await service.from('compliance_checks').insert(checks);
  await service.from('policy_acceptances').insert(['terms','fundraising_policy','privacy','acceptable_use'].map(policy_key=>({user_id:user.id,campaign_id:c.id,policy_key,policy_version:'2026-08-30'})));
  await service.from('audit_events').insert({actor_user_id:user.id,campaign_id:c.id,event_type:'campaign_submitted',entity_type:'campaign',entity_id:c.id,metadata:{reference_code:ref,risk_level:enhanced?'enhanced':'standard'}});
  if(user.email) await sendEmail({to:user.email,subject:`Good Cause application ${ref} received`,html:`<p>Thank you for submitting <strong>${body.title}</strong>.</p><p>Your reference is <strong>${ref}</strong>. Sign in to your fundraiser dashboard to upload evidence and follow the review.</p>`}).catch(()=>null);
  await createNotification({userId:user.id,campaignId:c.id,type:'campaign_submitted',title:`Application ${ref} received`,message:`${body.title} has been submitted for Good Cause review. Upload any requested verification evidence from your dashboard.`,email:null});
  await notifyAdmins({campaignId:c.id,type:'new_campaign_application',title:`New Good Cause application: ${ref}`,message:`${body.title} has been submitted for ${enhanced?'enhanced':'standard'} review. Review the campaign, documents, beneficiary and payment destination in the admin portal.`});
  return NextResponse.json({ok:true,id:c.id,referenceCode:ref});
}
