import Link from 'next/link';
import { CampaignCard } from '@/components/CampaignCard';
import { getPublicCampaigns } from '@/lib/public-campaigns';

export default async function Home() {
  const campaigns=await getPublicCampaigns(); const featured=campaigns[0];
  return <>
    <section className="hero refined-hero"><div className="shell hero-grid"><div className="hero-copy">
      <div className="kicker">New Zealand community fundraising</div><h1>Help where it matters.</h1>
      <p>Good Cause gives people a straightforward way to support verified community and humanitarian causes, with clear fees, careful review and accountable payouts.</p>
      <div className="hero-actions"><Link className="button" href={featured?`/campaigns/${featured.slug}`:'/campaigns'}>{featured?'Support a live cause':'Explore causes'}</Link><Link className="button secondary" href="/start">Start a cause</Link></div>
      <div className="trust-strip"><span>2.5% platform fee</span><span>Transparent payment processing</span><span>Campaigns reviewed before going live</span></div>
    </div><aside className="featured-appeal"><div className="appeal-visual nepal-visual large" aria-hidden="true"><div className="mountain mountain-one"></div><div className="mountain mountain-two"></div><div className="river"></div></div><div className="appeal-body"><div className="eyebrow">Good Cause</div><h2>{featured?featured.title:'Community fundraising built on trust'}</h2><p>{featured?featured.summary:'Fundraisers complete beneficiary, payment and compliance checks before a campaign can accept donations.'}</p><Link className="text-cta" href={featured?`/campaigns/${featured.slug}`:'/how-it-works'}>{featured?'View this cause':'See how it works'}</Link></div></aside></div></section>
    {featured&&<section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Featured cause</div><h2>Support a verified campaign</h2></div><p>Only approved campaigns appear publicly and can accept donations.</p></div><div className="grid-2"><CampaignCard campaign={featured}/><div className="impact-panel"><div className="impact-item"><strong>2.5%</strong><span>Good Cause platform fee</span></div><div className="impact-item"><strong>Clear</strong><span>fee and payout disclosure</span></div><div className="impact-item"><strong>Verified</strong><span>beneficiary and payout controls before donations are enabled</span></div></div></div></div></section>}
    <section className="section alt"><div className="shell"><div className="section-head"><div><div className="eyebrow">How it works</div><h2>Simple for supporters. Serious about trust.</h2></div></div><div className="grid-3"><div className="card feature"><div className="number">1</div><h3>Tell us about the cause</h3><p>Fundraisers explain who is raising funds, who benefits, what the money is for and provide evidence for review.</p></div><div className="card feature"><div className="number">2</div><h3>Good Cause reviews it</h3><p>Identity, beneficiary, payment destination, campaign purpose and risk checks are completed before donations are enabled.</p></div><div className="card feature"><div className="number">3</div><h3>Donate with clarity</h3><p>Supporters can see the campaign purpose, fee model, updates and fundraising progress.</p></div></div></div></section>
    <section className="section"><div className="shell fee-hero"><div className="eyebrow">Straightforward pricing</div><div className="fee-number">2.5% <small>platform fee</small></div><h2>No setup fee. No monthly fee.</h2><p className="muted">Payment-processing costs are deducted separately at the actual applicable Stripe rate.</p><Link className="button secondary" href="/fees">See the full fee breakdown</Link></div></section>
  </>;
}
