'use client';
import { FormEvent, useMemo, useState } from 'react';

type FormState = {
  fundraiserType:string; fullName:string; email:string; mobile:string; address:string;
  beneficiaryName:string; beneficiaryRelationship:string; beneficiaryCountry:string; beneficiaryConsent:boolean;
  title:string; category:string; purpose:string; target:string; evidence:string; paymentName:string; bankName:string; bankAccountNumber:string;
  truthful:boolean; authority:boolean; terms:boolean;
};

const initial:FormState = {fundraiserType:'individual_self',fullName:'',email:'',mobile:'',address:'',beneficiaryName:'',beneficiaryRelationship:'',beneficiaryCountry:'New Zealand',beneficiaryConsent:false,title:'',category:'Community',purpose:'',target:'',evidence:'',paymentName:'',bankName:'',bankAccountNumber:'',truthful:false,authority:false,terms:false};
const steps = ['Your details','Beneficiary','Campaign','Evidence & payment','Declarations','Review'];

export default function FundraiserApplication(){
  const [step,setStep]=useState(0); const [form,setForm]=useState<FormState>(initial); const [submitted,setSubmitted]=useState(false); const [reference,setReference]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const set=(key:keyof FormState,value:string|boolean)=>setForm(v=>({...v,[key]:value}));
  const isOther = form.fundraiserType === 'for_someone_else';
  const enhanced = useMemo(()=>isOther || form.beneficiaryCountry !== 'New Zealand' || Number(form.target||0)>=15000 || form.category==='Emergency relief',[form]);
  const next=()=>setStep(v=>Math.min(v+1,steps.length-1)); const back=()=>setStep(v=>Math.max(v-1,0));
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');const r=await fetch('/api/campaigns/apply',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const j=await r.json();if(r.status===401){window.location.href='/login?next=/start';return;}if(!r.ok){setError(j.error||'Unable to submit the application.');setBusy(false);return;}setReference(j.referenceCode||'');setSubmitted(true);setBusy(false)};
  if(submitted) return <div className="card success-panel"><div className="status-pill standard">Submitted safely</div><h2>Application received for review</h2><p>Your campaign has been securely saved and sent to Good Cause for review. You can now upload verification evidence and follow progress from your dashboard.</p>{reference&&<div className="review-summary"><strong>Reference</strong><span>{reference}</span></div>}<a className="button" href="/dashboard">Open fundraiser dashboard</a><div className="review-summary"><strong>Initial routing</strong><span>{enhanced?'Enhanced review':'Standard review'}</span></div></div>;
  return <form className="onboarding card" onSubmit={submit}>
    <div className="stepper">{steps.map((s,i)=><div className={`step ${i===step?'active':''} ${i<step?'done':''}`} key={s}><b>{i+1}</b><span>{s}</span></div>)}</div>
    <div className="onboarding-body">
      {step===0&&<><h2>Who is fundraising?</h2><p className="muted">We use this information to decide what verification is required.</p><label>Fundraiser type<select value={form.fundraiserType} onChange={e=>set('fundraiserType',e.target.value)}><option value="individual_self">Individual raising for myself</option><option value="for_someone_else">Individual raising for someone else</option><option value="charity">Registered charity</option><option value="community">Community organisation, club or society</option><option value="school">School or education organisation</option><option value="business">Business supporting a cause</option><option value="emergency">Emergency-relief organiser</option></select></label><div className="field-grid"><label>Full legal name<input value={form.fullName} onChange={e=>set('fullName',e.target.value)} required/></label><label>Email<input type="email" value={form.email} onChange={e=>set('email',e.target.value)} required/></label><label>Mobile<input value={form.mobile} onChange={e=>set('mobile',e.target.value)} required/></label><label>Residential or registered address<input value={form.address} onChange={e=>set('address',e.target.value)} required/></label></div><div className="notice">Identity documents are requested through a secure verification process before approval. Do not email identity documents to Good Cause.</div></>}
      {step===1&&<><h2>Who ultimately receives the money?</h2><label>Beneficiary or organisation name<input value={form.beneficiaryName} onChange={e=>set('beneficiaryName',e.target.value)} required/></label><div className="field-grid"><label>Your relationship to beneficiary<input value={form.beneficiaryRelationship} onChange={e=>set('beneficiaryRelationship',e.target.value)} placeholder="Self, parent, friend, authorised representative..." required/></label><label>Beneficiary country<select value={form.beneficiaryCountry} onChange={e=>set('beneficiaryCountry',e.target.value)}><option>New Zealand</option><option>Australia</option><option>Other overseas country</option></select></label></div>{isOther&&<label className="check"><input type="checkbox" checked={form.beneficiaryConsent} onChange={e=>set('beneficiaryConsent',e.target.checked)}/><span>I confirm the beneficiary knows about this application and has agreed to the fundraising activity. Good Cause may verify this directly.</span></label>}<div className="notice warning">Overseas beneficiaries and fundraising for another person are automatically routed to enhanced review.</div></>}
      {step===2&&<><h2>Describe the cause clearly</h2><label>Campaign title<input value={form.title} onChange={e=>set('title',e.target.value)} required/></label><div className="field-grid"><label>Category<select value={form.category} onChange={e=>set('category',e.target.value)}><option>Community</option><option>Emergency relief</option><option>Medical and wellbeing</option><option>Charity</option><option>Education</option><option>Community project</option><option>Other</option></select></label><label>Target amount, NZD<input type="number" min="1" value={form.target} onChange={e=>set('target',e.target.value)}/></label></div><label>Exactly what will donations be used for?<textarea rows={7} value={form.purpose} onChange={e=>set('purpose',e.target.value)} placeholder="Be specific. Explain the need, expected costs, who benefits and what happens if circumstances change." required/></label></>}
      {step===3&&<><h2>Evidence and payment destination</h2><label>Supporting evidence summary<textarea rows={5} value={form.evidence} onChange={e=>set('evidence',e.target.value)} placeholder="List bills, quotes, letters, organisation records or other evidence you can provide."/></label><div className="field-grid"><label>Bank account holder name<input value={form.paymentName} onChange={e=>set('paymentName',e.target.value)} required/></label><label>Bank name<input value={form.bankName} onChange={e=>set('bankName',e.target.value)} required/></label></div><label>Bank account number<input value={form.bankAccountNumber} onChange={e=>set('bankAccountNumber',e.target.value)} required/></label><div className="upload-placeholder"><strong>Secure evidence upload</strong><span>After you submit the campaign, upload identity, beneficiary, purpose and payment evidence from your private fundraiser dashboard.</span></div><div className="notice">Good Cause verifies the payment destination before a campaign can accept donations and may reconfirm it before payout.</div></>}
      {step===4&&<><h2>Required declarations</h2><p className="muted">Your declarations are stored with the campaign submission and policy version.</p><label className="check"><input type="checkbox" checked={form.truthful} onChange={e=>set('truthful',e.target.checked)}/><span>I confirm the information supplied is truthful, complete and not misleading.</span></label><label className="check"><input type="checkbox" checked={form.authority} onChange={e=>set('authority',e.target.checked)}/><span>I have authority to create this campaign and to provide the information submitted.</span></label><label className="check"><input type="checkbox" checked={form.terms} onChange={e=>set('terms',e.target.checked)}/><span>I agree to the Good Cause Terms, Fundraising Policy, Privacy Policy and Acceptable Use Policy.</span></label></>}
      {step===5&&<><h2>Review before submission</h2><div className="review-list"><div><span>Fundraiser</span><strong>{form.fullName||'Not supplied'}</strong></div><div><span>Beneficiary</span><strong>{form.beneficiaryName||'Not supplied'}</strong></div><div><span>Campaign</span><strong>{form.title||'Not supplied'}</strong></div><div><span>Target</span><strong>{form.target?`NZ$${Number(form.target).toLocaleString()}`:'No target entered'}</strong></div><div><span>Initial risk routing</span><strong>{enhanced?'Enhanced review':'Standard review'}</strong></div></div><div className="notice"><strong>No approval, no donations.</strong><br/>Submission sends the application to Good Cause moderation. The campaign cannot accept donations until all required checks are verified and a human reviewer approves it.</div></>}
    {error&&<div className="form-error">{error}</div>}</div>
    <div className="form-actions">{step>0&&<button type="button" className="button secondary" onClick={back}>Back</button>}<span/>{step<steps.length-1?<button type="button" className="button" onClick={next}>Continue</button>:<button className="button" disabled={!form.truthful||!form.authority||!form.terms||busy}>{busy?'Submitting...':'Submit for review'}</button>}</div>
  </form>
}
