import Link from 'next/link';
import { requireUser } from '@/lib/auth';
import { createServiceClient } from '@/lib/supabase-server';

export default async function Dashboard(){
  const {user,profile}=await requireUser();const s=createServiceClient();const isSuperAdmin=profile?.role==='super_admin';
  let query=s.from('campaigns').select('id,title,reference_code,status,risk_level,target_cents,created_at,owner_id').order('created_at',{ascending:false});
  if(!isSuperAdmin)query=query.eq('owner_id',user.id);
  const {data:campaignsData}=await query;const campaigns=campaignsData??[];
  return <><section className="cms-hero"><div className="shell"><div className="cms-hero-row"><div><div className="eyebrow">{isSuperAdmin?'Good Cause CMS':'Fundraiser dashboard'}</div><h1>{isSuperAdmin?'Campaign management':'Welcome'+(profile?.full_name?`, ${profile.full_name}`:'')}</h1><p>{isSuperAdmin?'Edit campaign content, publish media and manage every campaign from one place.':'Manage your campaigns, updates and payout progress.'}</p></div>{isSuperAdmin&&<span className="cms-role-badge">Super Admin</span>}</div></div></section><section className="cms-section"><div className="shell"><div className="cms-toolbar"><div><Link className="button" href="/start">Start a new cause</Link> <Link className="button secondary" href="/dashboard/notifications">Notifications</Link>{isSuperAdmin&&<> <Link className="button secondary" href="/admin">Admin centre</Link></>}</div><form action="/auth/signout" method="post"><button className="button secondary">Log out</button></form></div>{campaigns.length===0?<div className="card empty-state"><h2>No campaigns yet</h2><p>Create your first cause.</p><Link className="button" href="/start">Start a cause</Link></div>:<div className="cms-campaign-grid">{campaigns.map((c:any)=><Link href={`/dashboard/campaigns/${c.id}`} className="card cms-campaign-card" key={c.id}><div className="cms-campaign-top"><span className={`status-pill ${c.risk_level}`}>{String(c.status).replaceAll('_',' ')}</span><span className="cms-reference">{c.reference_code}</span></div><h3>{c.title}</h3><p>{c.target_cents?`Target NZ$${(c.target_cents/100).toLocaleString()}`:'No fixed target'}</p><strong>{isSuperAdmin?'Open in CMS':'Manage campaign'} →</strong></Link>)}</div>}</div></section></>;
}
